import type { Metadata } from "next";
import "./global.css"

export const metadata: Metadata = {
  title: "Created by Destiny",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string }
}>) {
  return (
    <html lang={locale}>
      <body>
        {children}
      </body>
    </html>
  );
}
